class CrateCSVConstants:
    REWARD_SHEET_NAME = "RewardSheetName"
    CRATE_TYPE = "CrateType"
    CRATE_NAME = "CrateName"
    PREVIEW_NAME = "Preview-Name"
    STARTING_KEYS = "StartingKeys"
    MAX_MASS_OPEN = "Max-Mass-Open"
    IN_GUI = "InGUI"
    SLOT = "Slot"
    OPENING_BROADCAST = "OpeningBroadCast"
    BROADCAST = "BroadCast"
    ITEM = "Item"
    GLOWING = "Glowing"
    NAME = "Name"
    LORE = "Lore"
    PREVIEW_TOGGLE = "Preview.Toggle"
    PREVIEW_CHEST_LINES = "Preview.ChestLines"
    PREVIEW_GLASS_TOGGLE = "Preview.Glass.Toggle"
    PREVIEW_GLASS_NAME = "Preview.Glass.Name"
    PREVIEW_GLASS_ITEM = "Preview.Glass.Item"
    PHYSICAL_KEY_NAME = "PhysicalKeyName"
    PHYSICAL_KEY_LORE = "PhysicalKeyLore"
    PHYSICAL_KEY_ITEM = "PhysicalKeyItem"
    PHYSICAL_KEY_GLOWING = "PhysicalKeyGlowing"
    HOLOGRAM_TOGGLE = "HologramToggle"
    HOLOGRAM_HEIGHT = "HologramHeight"
    HOLOGRAM_MESSAGE = "HologramMessage"

class RewardCSVConstants:
    DISPLAY_NAME = "DisplayName"
    DISPLAY_ITEM = "DisplayItem"
    DISPLAY_AMOUNT = "DisplayAmount"
    LORE = "Lore"
    MAX_RANGE = "MaxRange"
    CHANCE = "Chance"
    PERCENT_CHANCE = "PercentChance"
    ITEMS = "Items"
    AMOUNTS = "Amounts"
    COMMANDS = "Commands"
    MESSAGES = "Messages"

class CratePreviewFields:
    TOGGLE = "Toggle"
    CHEST_LINES = "ChestLines"
    GLASS = "Glass"
    GLASS_TOGGLE = "Toggle"
    GLASS_NAME = "Name"
    GLASS_ITEM = "Item"

class CrateFields:
    CRATE_TYPE = "CrateType"
    CRATE_NAME = "CrateName"
    PREVIEW_NAME = "Preview-Name"
    STARTING_KEYS = "StartingKeys"
    MAX_MASS_OPEN = "Max-Mass-Open"
    IN_GUI = "InGUI"
    SLOT = "Slot"
    OPENING_BROADCAST = "OpeningBroadCast"
    BROADCAST = "BroadCast"
    ITEM = "Item"
    GLOWING = "Glowing"
    NAME = "Name"
    LORE = "Lore"
    PHYSICAL_KEY = "PhysicalKey"
    PHYSICAL_KEY_NAME = "Name"
    PHYSICAL_KEY_LORE = "Lore"
    PHYSICAL_KEY_ITEM = "Item"
    PHYSICAL_KEY_GLOWING = "Glowing"
    HOLOGRAM = "Hologram"
    HOLOGRAM_TOGGLE = "Toggle"
    HOLOGRAM_HEIGHT = "Height"
    HOLOGRAM_MESSAGE = "Message"
    PREVIEW = "Preview"
    PRIZES = "Prizes"

class RewardFields:
    DISPLAY_NAME = "DisplayName"
    DISPLAY_ITEM = "DisplayItem"
    DISPLAY_AMOUNT = "DisplayAmount"
    LORE = "Lore"
    MAX_RANGE = "MaxRange"
    CHANCE = "Chance"
    ITEMS = "Items"
    COMMANDS = "Commands"
    MESSAGES = "Messages"